server:
  port: 8092    
spring:     #定义springmvc视图解析器
  mvc:    view:      prefix: /WEB-INF/views/
      suffix: .jsp


management:
  server:
    ssl:
      enabled: false
      
dubbo:
  scan:
    basePackages: com.jt
  application:
    name: consumer-jt-web
  registry:
    address: zookeeper://192.168.92.135:2181?backup=192.168.92.135:2182,192.168.92.135:2183